import jsPDF from "jspdf";
import { backendClient } from "@/integrations/backend/client";

export interface FeeRow {
  course_name: string;
  course_slug: string;
  fee_amount: number;
  fee_type: string;
  year: string;
}

export async function fetchCourseFees(collegeSlug: string): Promise<FeeRow[]> {
  const { data } = await (backendClient as any)
    .from("course_fees")
    .select("course_name, course_slug, fee_amount, fee_type, year")
    .eq("college_slug", collegeSlug)
    .order("course_name", { ascending: true });
  return data || [];
}

function fmtINR(n: number) {
  if (!n || isNaN(n)) return "-";
  return "INR " + Number(n).toLocaleString("en-IN");
}

export async function downloadCourseFeePDF(opts: { collegeSlug: string; collegeName: string }) {
  const rows = await fetchCourseFees(opts.collegeSlug);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 50;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(opts.collegeName, 40, y);
  y += 22;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text("Course & Fee Structure", 40, y);
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 20;

  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Course", 40, y);
  doc.text("Fee", 320, y);
  doc.text("Type", 420, y);
  doc.text("Year", 500, y);
  y += 6;
  doc.line(40, y, W - 40, y);
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  if (rows.length === 0) {
    doc.setTextColor(120);
    doc.text("No published fee data yet. Our counsellor will share the latest fees.", 40, y);
  } else {
    for (const r of rows) {
      if (y > 760) {
        doc.addPage();
        y = 50;
      }
      const name = doc.splitTextToSize(r.course_name || r.course_slug, 260);
      doc.text(name, 40, y);
      doc.text(fmtINR(r.fee_amount), 320, y);
      doc.text(r.fee_type || "-", 420, y);
      doc.text(r.year || "-", 500, y);
      y += Math.max(16, name.length * 12);
    }
  }

  y += 30;
  if (y > 760) { doc.addPage(); y = 50; }
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 18;
  doc.setTextColor(120);
  doc.setFontSize(9);
  doc.text("Generated by DekhoCampus · Founded by IIT Delhi Alumni", 40, y);

  const safe = opts.collegeName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`${safe}-course-and-fees.pdf`);
}
