import jsPDF from "jspdf";
import logo from "@/assets/dekhocampus-logo.png";

export type RoadmapData = {
  verdict?: string;
  entranceExams?: { name: string; why?: string; targetScore?: string; officialUrl?: string }[];
  milestones?: { phase: string; focus?: string; tasks?: string[] }[];
  weeklyPlan?: {
    subjects?: { subject: string; hoursPerWeek?: number; approach?: string; topPriorityChapters?: string[] }[];
    mockSchedule?: string;
  };
  books?: { subject: string; books: string[] }[];
  freeResources?: { name: string; url?: string; use?: string }[];
  backupColleges?: { name: string; exam?: string; why?: string }[];
  redFlags?: string[];
  mentorNote?: string;
};

export type RoadmapMeta = {
  targetCollege: string;
  targetCourse?: string;
  classLevel: string;
  stream?: string;
  studentName?: string;
};

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch(logo);
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const r = new FileReader();
      r.onload = () => resolve(r.result as string);
      r.onerror = () => resolve(null);
      r.readAsDataURL(blob);
    });
  } catch { return null; }
}

export async function downloadRoadmapPDF(data: RoadmapData, meta: RoadmapMeta) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 42; // margin
  let y = 0;

  const COLOR_PRIMARY: [number, number, number] = [234, 88, 12]; // orange-600
  const COLOR_DARK: [number, number, number] = [15, 23, 42];
  const COLOR_MUTED: [number, number, number] = [100, 116, 139];

  const ensureSpace = (need: number) => {
    if (y + need > H - 60) {
      footer();
      doc.addPage();
      y = M;
      pageHeader();
    }
  };

  const pageHeader = () => {
    doc.setFillColor(...COLOR_PRIMARY);
    doc.rect(0, 0, W, 4, "F");
    y = Math.max(y, M);
  };

  const footer = () => {
    const py = H - 28;
    doc.setDrawColor(230); doc.line(M, py - 8, W - M, py - 8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLOR_MUTED);
    doc.text("Generated by DekhoCampus · dekhocampus.com · AI-generated, verify on official sources.", W / 2, py + 4, { align: "center" });
    const pno = doc.getNumberOfPages();
    doc.text(`Page ${pno}`, W - M, py + 4, { align: "right" });
  };

  const h1 = (text: string) => {
    ensureSpace(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(...COLOR_PRIMARY);
    doc.text(text, M, y);
    y += 8;
    doc.setDrawColor(...COLOR_PRIMARY);
    doc.setLineWidth(1.2);
    doc.line(M, y, M + 40, y);
    y += 16;
    doc.setLineWidth(0.5);
  };

  const para = (text: string, opts?: { bold?: boolean; size?: number; color?: [number, number, number] }) => {
    const size = opts?.size ?? 10.5;
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...(opts?.color ?? COLOR_DARK));
    const lines = doc.splitTextToSize(text, W - M * 2);
    ensureSpace(lines.length * (size + 3));
    doc.text(lines, M, y);
    y += lines.length * (size + 3) + 4;
  };

  const bullet = (text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...COLOR_DARK);
    const lines = doc.splitTextToSize(text, W - M * 2 - 14);
    ensureSpace(lines.length * 13 + 4);
    doc.setFillColor(...COLOR_PRIMARY);
    doc.circle(M + 3, y - 3, 1.6, "F");
    doc.text(lines, M + 12, y);
    y += lines.length * 13 + 2;
  };

  // ==== COVER PAGE ====
  pageHeader();
  const logoData = await loadLogoDataUrl();
  if (logoData) {
    // Centered big logo top
    const lw = 180, lh = 64;
    try { doc.addImage(logoData, "PNG", (W - lw) / 2, 60, lw, lh, undefined, "FAST"); } catch {}
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(...COLOR_PRIMARY);
    doc.text("DekhoCampus", W / 2, 100, { align: "center" });
  }

  // Tagline
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_MUTED);
  doc.text("India's GenZ college discovery platform", W / 2, 140, { align: "center" });

  // Title block
  y = 200;
  doc.setFillColor(255, 247, 237);
  doc.roundedRect(M, y, W - M * 2, 160, 14, 14, "F");
  y += 32;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_PRIMARY);
  doc.text("YOUR LOCKED TARGET", W / 2, y, { align: "center" });
  y += 28;
  doc.setFontSize(22);
  doc.setTextColor(...COLOR_DARK);
  const titleLines = doc.splitTextToSize(meta.targetCollege, W - M * 2 - 40);
  doc.text(titleLines, W / 2, y, { align: "center" });
  y += titleLines.length * 24 + 6;
  if (meta.targetCourse) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(...COLOR_MUTED);
    doc.text(meta.targetCourse, W / 2, y, { align: "center" });
    y += 18;
  }
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_MUTED);
  doc.text(`Class ${meta.classLevel} · ${meta.stream || "Science"} · Roadmap dated ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, W / 2, y, { align: "center" });

  y = 410;
  doc.setDrawColor(255, 200, 150);
  doc.line(M + 40, y, W - M - 40, y);
  y += 30;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_MUTED);
  doc.text("\"A goal without a plan is just a wish. This is your plan.\"", W / 2, y, { align: "center" });

  // Cover footer with confidentiality
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("This roadmap is AI-generated. Cross-check exam dates, cut-offs and syllabus on official sources before acting.", W / 2, H - 60, { align: "center" });
  footer();

  // ==== CONTENT PAGES ====
  doc.addPage();
  y = M;
  pageHeader();

  if (data.verdict) { h1("Reality Check"); para(data.verdict); }

  if (data.entranceExams?.length) {
    h1("Entrance Exams You Must Crack");
    data.entranceExams.forEach((e) => {
      ensureSpace(40);
      doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...COLOR_DARK);
      doc.text(e.name, M, y); y += 14;
      if (e.targetScore) { para(`Target: ${e.targetScore}`, { bold: true, color: COLOR_PRIMARY, size: 10 }); }
      if (e.why) { para(e.why, { size: 10 }); }
      if (e.officialUrl) { para(`Official: ${e.officialUrl}`, { size: 9, color: COLOR_MUTED }); }
      y += 4;
    });
  }

  if (data.milestones?.length) {
    h1("Phase-by-Phase Roadmap");
    data.milestones.forEach((m) => {
      ensureSpace(30);
      doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...COLOR_PRIMARY);
      doc.text(m.phase, M, y); y += 14;
      if (m.focus) para(m.focus, { size: 10, color: COLOR_MUTED });
      m.tasks?.forEach((t) => bullet(t));
      y += 6;
    });
  }

  if (data.weeklyPlan?.subjects?.length) {
    h1("Weekly Subject Plan");
    data.weeklyPlan.subjects.forEach((s) => {
      ensureSpace(34);
      doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...COLOR_DARK);
      doc.text(`${s.subject}${s.hoursPerWeek ? ` · ${s.hoursPerWeek} hrs/week` : ""}`, M, y); y += 13;
      if (s.approach) para(s.approach, { size: 10 });
      if (s.topPriorityChapters?.length) {
        para("Priority chapters: " + s.topPriorityChapters.join(", "), { size: 9, color: COLOR_MUTED });
      }
      y += 4;
    });
    if (data.weeklyPlan.mockSchedule) para("Mocks: " + data.weeklyPlan.mockSchedule, { bold: true, size: 10 });
  }

  if (data.books?.length) {
    h1("Recommended Books");
    data.books.forEach((b) => bullet(`${b.subject}: ${b.books.join(" · ")}`));
  }

  if (data.freeResources?.length) {
    h1("Free Resources");
    data.freeResources.forEach((r) => bullet(`${r.name}${r.use ? ` - ${r.use}` : ""}${r.url ? ` (${r.url})` : ""}`));
  }

  if (data.backupColleges?.length) {
    h1("Backup Colleges (Plan B)");
    data.backupColleges.forEach((c) => bullet(`${c.name}${c.exam ? ` · via ${c.exam}` : ""}${c.why ? ` - ${c.why}` : ""}`));
  }

  if (data.redFlags?.length) {
    h1("Watch Out For");
    data.redFlags.forEach((r) => bullet(r));
  }

  if (data.mentorNote) {
    h1("Mentor Note");
    para(data.mentorNote, { size: 10.5 });
  }

  // disclaimer
  ensureSpace(40);
  y += 10;
  doc.setDrawColor(230); doc.line(M, y, W - M, y); y += 14;
  para("NOTE: This roadmap is AI-generated by DekhoCampus. We do not guarantee outcomes - actual results depend on exam patterns, cut-offs, and official notifications. Always cross-check on the official conducting body's website. Found an issue? Report it on dekhocampus.com/lock-target.", { size: 8.5, color: COLOR_MUTED });

  footer();

  const safe = meta.targetCollege.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase().slice(0, 60);
  doc.save(`dekhocampus-roadmap-${safe}.pdf`);
}
